---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: copy hosts file to position
      copy:
        src: files/hosts
        dest: /etc/ansible/hosts
        owner: root
        group: root
        mode: 0440

    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"
 
    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu", "Raspbian"]

    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist
      when: ansible_distribution in ["Debian", "Ubuntu", "Raspbian"]

    - name: Set timezone to Europe/Berlin
      community.general.timezone:
        name: Europe/Berlin

  tasks: 

  - name: install packages
    package:
      name: 
        - htop
        - nano
        - borgbackup
        - tmux

  - name: add syncthing user
    user:
      name: syncthingadmin
      system: yes
    when: "'syncthingserver' in group_names"

  - name: add ansible user
    user:
      name: ansibleadmin
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansibleadmin
      dest: /etc/sudoers.d/ansibleadmin
      owner: root
      group: root
      mode: 0440
 
  - name: add ansible-pull cron job for Raspbian and Ubuntu
    cron:
      name: ansible auto-provision
      user: ansibleadmin
      minute: "17"
      hour: "*/6"
      job: /usr/local/bin/ansible-pull -o -U https://github.com/SteevieBDE/ansible_setup.git
    when: "('longserver' in group_names) or ('ungrouped' in group_names)"

  - name: add ansible-pull cron job for Debian
    cron:
      name: ansible auto-provision
      user: ansibleadmin
      minute: "17"
      hour: "*/6"
      job: /usr/bin/ansible-pull -o -U https://github.com/SteevieBDE/ansible_setup.git
    when: "'shortserver' in group_names"

