---
- hosts: localhost
  connection: local
  become: true
  
  tasks: 
  - name: install packages
    package:
      name: 
        - htop
        - git
        - nano

  - name: add ansible user
    user:
      name: ansibleadmin
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansibleadmin
      dest: /etc/sudoers.d/ansibleadmin
      owner: root
      group: root
      mode: 0440
 
  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansibleadmin
      minute: "*/30"
      job: ansible-pull -o -U https://github.com/SteevieBDE/ansible_setup.git

