---
- hosts: localhost
  connection: local
  become: true

  vars:
    my_version: 2.8.5

  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Set timezone to Europe/Berlin if version is 2.9.0 or higher
      community.general.timezone:
        name: Europe/Berlin  
      when: my_version is version('2.8.9', '>')



  tasks: 

  - name: install packages
    package:
      name: 
        - htop
        - nano
        - borgbackup

  - name: add ansible user
    user:
      name: ansibleadmin
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansibleadmin
      dest: /etc/sudoers.d/ansibleadmin
      owner: root
      group: root
      mode: 0440
 
  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansibleadmin
      minute: "*/30"
      job: ansible-pull -o -U https://github.com/SteevieBDE/ansible_setup.git
